Fix typechecking
God, this was terrible to figure out.

Parcel is lovely and magical, but its module resolution was a bit too
magical for TypeScript. In `index.ts`, Parcel references the Rust crate
by importing the `Cargo.toml` file:

```ts
import wasm from "../crate/Cargo.toml"
```

Parcel understands this, but TypeScript doesn't and freaks out:

```
src/index.ts:2:18 - error TS2792: Cannot find module '../crate/Cargo.toml'.
Did you mean to set the 'moduleResolution' option to 'node', or to add
aliases to the 'paths' option?
```

I mean, no I didn't, but thanks for trying. Anyways, there are two
issues:

- TS can't resolve the import _at all_ because it can't handle non-JS
- TS _definitely_ can't see the typings generated by wasm-bindgen

I played around with many permutations of `tsconfig.json` options,
ranging from `files`, `include`, `baseUrl`, `paths`, and so on. None of
them proved very helpful. In the end, here is what worked:

1. Heeding [this comment](https://github.com/rustwasm/wasm-bindgen/issues/182#issuecomment-487928242), define a wildcard module declaration (TS's way
of handling non-JS loaders) and use `typeof` to infer the types produced
by wasm-bindgen

    ```ts
    declare module "*.toml" {
        const value: typeof import("../crate/pkg/rust_parcel")
        export default value
    }
    ```
2. Import `index.d.ts` at the top of `index.ts`, as a dependency for the
`Cargo.toml` import:

    ```ts
    /// <reference path="./index.d.ts" />
    import wasm from "../crate/Cargo.toml"
    ```

I needed both steps 1 and 2 to get it to work. Step 1 alone works if
your `tsconfig.json` uses the `files` property, but it doesn't work if
you use `includes` with the same argument.

```json
{
    "files": [
        "./src/index.d.ts",
        "./src/index.ts"
    ]
}
```

Anyways, I now know more than I ever wanted to know about TypeScript.